# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Event.destroy_all

Event.create!(title: "Welcome to Web Summit", description: "Welcome to Web Summit 2024 at Centre Stage with Luís Montenegro (Prime Minister @ Government of Portugal), Carlos Moedas (Mayor @ City of Lisbon) and Paddy Cosgrave (CEO & Founder @ Web Summit)", start_time: "2024-11-11 18:00:00", end_time: "2024-11-11 18:20:00")
Event.create!(title: "Transforming CO2 into jet fuel", description: "at Centre Stage. Etosha joins us a few weeks after her carbon transformation company raised a whopping $645 million. The funding is fuelling her mission towards decarbonising the aviation industry. But why stop there? It has the potential to defossilise all manufacturing, enabling the creation of everyday products made from air. This innovation could revolutionise our battle against global warming. with Etosha Cave (Co-Founder and Chief Science Officer @ Twelve) and Amy Nordrum (Executive Editor @ MIT Technology Review)", start_time: "2024-11-11 18:25:00", end_time: "2024-11-11 18:45:00")
Event.create!(title: "The great AI debate: Who decides our future?", description: "at Centre Stage. What are the ethical implications of AI’s breakneck development? Should we accelerate it to help solve crises like global warming, or should we be more concerned about the potential ramifications of AI everywhere all at once? Join our expert panel discussion on arguably the most critical public policy issue of our time. With Max Tegmark (President @ Future of Life Institute), Thomas Wolf (Co-founder & Chief Science Officer @ Hugging Face) and Nick Thompson (CEO @ The Atlantic)", start_time: "2024-11-11 18:45:00", end_time: "2024-11-11 19:05:00")
Event.create!(title: "Culture x commerce", description: "at Centre Stage. Join Frank Cooper III, CMO of Visa and GRAMMY® Award-winning, Academy Award®-nominated musician and filmmaker, entrepreneur, and philanthropist Pharrell Williams to discuss the intersection of Culture and Commerce. In the age of social media, creators play a crucial role in shaping culture, which is having a significant impact on commerce. Frank and Pharrell will explore the process of 'making it', the integral role of technology, the importance of philanthropy, and how businesses and individuals can harness the power of the creator economy. With Pharrell Williams (Artist and Entrepreneur), Frank Cooper (CMO @ Visa)", start_time: "2024-11-11 19:05:00", end_time: "2024-11-11 19:35:00")
Event.create!(title: "Breakout Startups", description: "at Centre Stage. With Mário Tarouca (Co-founder & COO @ Framedrop.ai), Ioana Surdu-Bob (Co-Founder, COO @ Konvi), Ryan Donnelly (Founder @ Enzai), Barinder Rasode (Co-Founder & CEO @ Tersa Earth), Valentina Jordan (Co-Founder & CEO @ Nauta) and Prashanth Balasubramanian (CEO & CTO @ Striga)", start_time: "2024-11-12 09:25:00", end_time: "2024-11-12 09:45:00")
Event.create!(title: "One smol step for AI…", description: "at Centre Stage. With models growing exponentially larger in size and soaring compute costs, the desire for more curated and thoughtfully trained language models is on the rise. Join Hugging Face’s Co-founder & CSO Thomas Wolf as he breaks down this discrepancy in supply and demand and shares his team's work on SmolLM, a new family of models that emphasizes data quality over size. With Thomas Wolf (Co-founder & Chief Science Officer @ Hugging Face) and Zach Seward (Editorial Director of A.I. @ The New York Times)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 10:20:00")
Event.create!(title: "Opening remarks with Antonia-Denisa Efron", description: "at Stage 7. With Antonia-Denisa Efron (Managing Director of Competence Hub Europe @ Siemens Energy)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 10:15:00")
Event.create!(title: "Opening remarks with Eamonn Carey", description: "at Stage 8. Eamonn Carey presents our opening remarks for the first day of SaaS Summit. With Eamonn Carey (General Partner @ Tera Ventures)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 10:15:00")
Event.create!(title: "Rise and shine: A Vancouver-inspired yoga experience", description: "at Stage 10. Join Zoe from Ministry of Yoga, Lisbon, for a refreshing escape with a gentle yoga practice inspired by Vancouver's wellness ethos. Start your first morning at Web Summit feeling rejuvenated and centred, with clear intentions for the exciting events ahead. This session is brought to you by the delegation from Vancouver, British Columbia, Canada. #VancouverVibesInLisbon. (Standing yoga session, no special clothing required)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 10:30:00")
Event.create!(title: "Opening remarks with Francois Chadwick", description: "at Stage 14. With Francois Chadwick (Partner @ KPMG)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 10:15:00")
Event.create!(title: "Opening remarks", description: "at Stage 15. With Danny Frietman (Co-founder @ New Dutch Wave)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 10:10:00")
Event.create!(title: "Opening remarks with Toby Daniels", description: "at Stage 16. With Toby Daniels (Co-founder @ ON_Discourse)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 10:15:00")
Event.create!(title: "PITCH Group 1", description: "at Stage 6. 105 of the most promising startups will battle it out in the group rounds of the competition. In this round, 10 of them will fight for a chance to move onto the semi-final. Competing startups will have three minutes to pitch, followed by a three-minute Q&A with our judging panel. With Anas CHANAA (CEO @ Nucleon Security), Alex Santos (CEO @ Barifix), Yaroslav Krempovych (General Manager @ Checkbox), Alexandre Ferreira (CTO @ outGoing), Ksenia Belkina (CEO @ Cardiomo) and Moaad El Aboudi (CEO @ Insight Solutions SA)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 11:00:00")
Event.create!(title: "PITCH Group 2", description: "at Stage 9. 105 of the most promising startups will battle it out in the group rounds of the competition. In this round, 10 of them will fight for a chance to move onto the semi-final. Competing startups will have three minutes to pitch, followed by a three-minute Q&A with our judging panel. With Albert Brenner (Managing Director & Co-Founder @ OVRLAY), Esra Akdere (Co-Founder @ Time Travel VR Tour), Andreia Trigo (CEO @ Enhanced Fertility), Ryan Schmaltz (CEO @ Patient Ready, Inc.), Ksenia Belkina (CEO @ Cardiomo) and Anna Franziska Michel (CEO & Founder @ yoona.ai)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 11:00:00")
Event.create!(title: "PITCH Group 3", description: "at Stand 12. 105 of the most promising startups will battle it out in the group rounds of the competition. In this round, 10 of them will fight for a chance to move onto the semi-final. Competing startups will have three minutes to pitch, followed by a three-minute Q&A with our judging panel. With Federico Leuze (AI Developer @ Resonisk), Mila (Ludmila) Aleshina (Co-founder @ incorpo studio), Emmanuel Evarist-Chika (CEO & Co-founder @ LINK), Heather Mitche (Chief of staff @ Innerworks), Jeff Hu (CEO & Founder @ Turing Space) and Brittany Kaiser (Founder @ Own Your Data)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 11:00:00")
Event.create!(title: "Meet the Adobe Experts", description: "at Stand E111. Meet with our experts to explore ways you can accelerate creative productivity with the power of generative AI within your team and organization. See a live demo or schedule a meeting with us!", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 12:30:00")
Event.create!(title: "Express Yourself with Adobe Express", description: "at Stand E111. Join us at the Adobe Express activation! Unleash your creativity by personalizing your own coffee mug. The perfect way to express yourself and create a unique piece with Adobe Express. The quick and easy create-anything app.", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 11:00:00")
Event.create!(title: "How to prepare for the age of AI in software", description: "at Roundtable. Kirill Skrygan, CEO of JetBrains, leads a discussion on how AI is transforming software development, from workflow changes to new skills. Explore the challenges and opportunities AI brings to building modern software products. With Kirill Skrygan (CEO @ JetBrains)", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 11:00:00")
Event.create!(title: "Making sense of the US elections", description: "at Roundtables. The results of American elections will have a profound (though not necessarily straightforward) impact on technology in the US and beyond. Join us to talk about how the November 2024 U.S. election might reshape the technological landscape in the years to come.", start_time: "2024-11-12 10:00:00", end_time: "2024-11-12 11:00:00")
Event.create!(title: "Navigating the EU AI act", description: "at Stage 15. The EU's new AI Act ushers in a transformative era of regulation for artificial intelligence. While the Act aims to ensure responsible development and use of AI, it also presents significant compliance challenges for companies. This panel delves deep into the Act's key provisions and explores the potential difficulties businesses might face during implementation. With Shelley McKinley (Chief Legal Officer @ Github), Adriano Koshiyama (Co-CEO & Co-Founder @ Holistic AI), Tasos Stampelos (Head of EU Public Policy @ Mozilla) and Ryan Browne (Correspondent @ CNBC)", start_time: "2024-11-12 10:10:00", end_time: "2024-11-12 10:35:00")
