# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Event.destroy_all

Event.create!(title: "Opening Address | Deep Tech Momentum", description: "at DaVinci Stage with Martin Schilling (CEO & Co-Founder @ Deep Tech Momentum) and Isabelle Flanagan (COO & Co-Founder @ Deep Tech Momentum)", start_time: "2024-05-13 09:30:00", end_time: "2024-05-13 10:00:00")
Event.create!(title: "Virtual Talk | Welcome Address DTM25 by EU Startup Commissioner", description: "at DaVinci Stage with Ekaterina Zaharieva (European Commissioner for Startups)", start_time: "2024-05-13 10:00:00", end_time: "2024-05-13 10:30:00")
Event.create!(title: "Innovators Unleashed | Novel AI", description: "at DaVinci Stage. Three visionaries deliver rapid-fire provocations on how Novel AI will reshape entire sectors within the next decade. This is no ordinary panel: expect bold predictions, fierce debate, and real-time challenges as speakers defend their visions against critical counterpoints. The session culminates with an audience Q&A. With Björn Tremmerie (Head of Venture Capital and Impact Investing @ European Investment Fund), Rasmus Rothe (Founder of Merantix @ Merantix Capital) and Vanessa Cann (Managing Director / Data & AI Innovation Lead @ Accenture)", start_time: "2024-05-13 10:30:00", end_time: "2024-05-13 11:30:00")
Event.create!(title: "Innovators Unleashed | Clean Energy & Circular Economy", description: "Three visionaries deliver rapid-fire provocations on how Clean Energy & Circular Economy will reshape entire sectors within the next decade. This is no ordinary panel: expect bold predictions, fierce debate, and real-time challenges as speakers defend their visions against critical counterpoints. The session culminates with an audience Q&A. With Fabian Heilemann (Founder & CEO @ AENU), Marie-Helene Ametsreiter (General Partner @ Speedinvest) and Mikela Druckman (CEO & Co-Founder @ Greyparrot)", start_time: "2024-05-13 10:45:00", end_time: "2024-05-13 11:45:00")
Event.create!(title: "Innovators Unleashed | New Space", description: "at Curie Stage with Daniel Metzler (CEO @ Isar Aerospace), Bulent Altan (Founding Partner @ Alpine Space Ventures) and Walter Ballheimer (CEO @ Reflex Aerospace)", start_time: "2024-05-13 10:45:00", end_time: "2024-05-13 11:45:00")
Event.create!(title: "Innovators Unleashed | Robotics & Industrial Tech", description: "at Copernicus Stage. Three visionaries deliver rapid-fire provocations on how Robotics & Industrial Tech will reshape entire sectors within the next decade. This is no ordinary panel: expect bold predictions, fierce debate, and real-time challenges as speakers defend their visions against critical counterpoints. The session culminates with an audience Q&A. With Axel Deniz (CEO Bosch Business Innovations @ Bosch Global), David Reger (CEO @ NEURA Robotics) and Sébastien Lefebvre (Partner @ Elaia)", start_time: "2024-05-13 10:45:00", end_time: "2024-05-13 11:45:00")
Event.create!(title: "Innovators Unleashed | Bio Builders", description: "at DaVinci Stage. Three visionaries deliver rapid-fire provocations on how Bio Builders will reshape entire sectors within the next decade. This is no ordinary panel: expect bold predictions, fierce debate, and real-time challenges as speakers defend their visions against critical counterpoints. The session culminates with an audience Q&A. With Detlev Riesner (Co-Founder @ QIAGEN), Jakob Uszkoreit (Chief Executive Officer @ Inceptive) and Max Bautin (Managing Partner, co-founder @ IQ Capital)", start_time: "2024-05-13 10:30:00", end_time: "2024-05-13 12:30:00")
Event.create!(title: "Innovators Unleashed | Resilience & Cyber-Security", description: "at Lovelace Stage. Three visionaries deliver rapid-fire provocations on how Resilience & Cyber-Security will reshape entire sectors within the next decade. This is no ordinary panel: expect bold predictions, fierce debate, and real-time challenges as speakers defend their visions against critical counterpoints. The session culminates with an audience Q&A. With Sven Weizenegger (Chairman of the Management Board @ Bundeswehr Cyber Innovation Hub), Kelly Chen (Founding Partner @ NATO Innovation Fund) and Max Makarchuk (Head of AI / ML Products @ Brave1)", start_time: "2024-05-13 11:45:00", end_time: "2024-05-13 12:45:00")
Event.create!(title: "Innovators Unleashed | Smart Mobility & Electrification", description: "at Curie Stage. Three visionaries deliver rapid-fire provocations on how Smart Mobility & Electrification will reshape entire sectors within the next decade. This is no ordinary panel: expect bold predictions, fierce debate, and real-time challenges as speakers defend their visions against critical counterpoints. The session culminates with an audience Q&A. With Manuel Yoon (GM Germany @ Autobrains), Christian Miele (General Partner @ Headline) and Hendrik Brandis (Co-Founder and Partner @ Earlybird Venture Capital)", start_time: "2024-05-13 11:45:00", end_time: "2024-05-13 12:45:00")
Event.create!(title: "Innovators Unleashed | Future of Computing", description: "at Copernicus Stage. Three visionaries deliver rapid-fire provocations on how Future of Computing will reshape entire sectors within the next decade. This is no ordinary panel: expect bold predictions, fierce debate, and real-time challenges as speakers defend their visions against critical counterpoints. The session culminates with an audience Q&A. With Hermann Hauser (Co-Founder and Partner @ Amadeus Capital Partners), Nader Sabbaghian (Partner @ 360 Capital) and Jan Goetz (CEO & Co-Founder @ IQM Quantum Computers)", start_time: "2024-05-13 11:45:00", end_time: "2024-05-13 12:45:00")
